package com.mycompany.supermarket_project.forms.change_info_form;

import com.mycompany.supermarket_project.model.Employee;
import javax.swing.JOptionPane;
import com.mycompany.supermarket_project.*;
import utility.database_navigation.*;

public class ChangeOwnInfoForm extends javax.swing.JFrame {

    public ChangeOwnInfoForm() {
        initComponents();
        showInfo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        idInput = new javax.swing.JTextField();
        idLable = new javax.swing.JLabel();
        nameInput = new javax.swing.JTextField();
        nameLbl = new javax.swing.JLabel();
        mobileInput = new javax.swing.JTextField();
        mobileLbl = new javax.swing.JLabel();
        ageLbl = new javax.swing.JLabel();
        ageInput = new javax.swing.JTextField();
        emailInput = new javax.swing.JTextField();
        emailLbl = new javax.swing.JLabel();
        addressLbl = new javax.swing.JLabel();
        addressInput = new javax.swing.JTextField();
        passwordInput = new javax.swing.JPasswordField();
        passwordLbl = new javax.swing.JLabel();
        saveChangeBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Change My Information");

        idInput.setEditable(false);

        idLable.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        idLable.setForeground(new java.awt.Color(255, 102, 0));
        idLable.setText("ID");

        nameLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 102, 0));
        nameLbl.setText("Name");

        mobileLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        mobileLbl.setForeground(new java.awt.Color(255, 102, 0));
        mobileLbl.setText("Mobile Number");

        ageLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ageLbl.setForeground(new java.awt.Color(255, 102, 0));
        ageLbl.setText("age");

        emailLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        emailLbl.setForeground(new java.awt.Color(255, 102, 0));
        emailLbl.setText("Email");

        addressLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        addressLbl.setForeground(new java.awt.Color(255, 102, 0));
        addressLbl.setText("Address");

        addressInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressInputActionPerformed(evt);
            }
        });

        passwordLbl.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        passwordLbl.setForeground(new java.awt.Color(255, 102, 0));
        passwordLbl.setText("Password");

        saveChangeBtn.setBackground(new java.awt.Color(255, 102, 0));
        saveChangeBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        saveChangeBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveChangeBtn.setText("Save Changes");
        saveChangeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveChangeBtnMouseClicked(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(255, 102, 0));
        cancelBtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setText("Cancel");
        cancelBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mobileLbl)
                            .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ageInput, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                            .addComponent(mobileInput))))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addressInput, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                    .addComponent(nameInput)
                    .addComponent(emailInput))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addComponent(saveChangeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addComponent(cancelBtn)
                .addGap(131, 131, 131))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(idLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(587, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobileInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mobileLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ageInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ageLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordInput, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveChangeBtn)
                    .addComponent(cancelBtn))
                .addGap(57, 57, 57))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(idLable, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(284, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showInfo() {
        Employee emp = Supermarket.currentEmplyee;
        idInput.setText(emp.getId() + "");
        nameInput.setText(emp.getName());
        mobileInput.setText(emp.getPhoneNumber());
        emailInput.setText(emp.getEmail());
        addressInput.setText(emp.getAddress());
        ageInput.setText(emp.getAge() + "");
        passwordInput.setText(emp.getPassword());
    }

    private void addressInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addressInputActionPerformed

    }// GEN-LAST:event_addressInputActionPerformed

    private void cancelBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_cancelBtnMouseClicked

        this.dispose();
    }// GEN-LAST:event_cancelBtnMouseClicked

    public boolean checkEmptyInputs() {
        if (idInput.getText().length() == 0 ||
                nameInput.getText().length() == 0 ||
                mobileInput.getText().length() == 0 ||
                ageInput.getText().length() == 0 ||
                emailInput.getText().length() == 0 ||
                addressInput.getText().length() == 0 ||
                passwordInput.getPassword().length == 0) {
            JOptionPane.showMessageDialog(this, "You have entered All Fields");
            return false;
        }
        return true;
    }

    private void saveChangeBtnMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_saveChangeBtnMouseClicked
        if (checkEmptyInputs() &&
                utility.Utilities.isValidLong(this, idInput.getText()) &&
                utility.Utilities.isValidInteger(this, ageInput.getText()) &&
                utility.Utilities.passwordValidation(this, passwordInput.getPassword())) {
            
            employeeDB empDB = new employeeDB();
            int res = empDB.updateEmployeeById(
                Supermarket.currentEmplyee.getId(),
                nameInput.getText(),
                mobileInput.getText(),
                Integer.parseInt(ageInput.getText()),
                emailInput.getText(),
                addressInput.getText(),
                new String(passwordInput.getPassword()),
                Supermarket.currentEmplyee.getRole()
            );
            if(res != -1 && res != 0){
                JOptionPane.showMessageDialog(this, "Info updated Successfully");
            }else{
                JOptionPane.showMessageDialog(this, "something went wrong");
            }
        }
    }// GEN-LAST:event_saveChangeBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeOwnInfoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeOwnInfoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeOwnInfoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeOwnInfoForm.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeOwnInfoForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressInput;
    private javax.swing.JLabel addressLbl;
    private javax.swing.JTextField ageInput;
    private javax.swing.JLabel ageLbl;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField emailInput;
    private javax.swing.JLabel emailLbl;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLable;
    private javax.swing.JTextField mobileInput;
    private javax.swing.JLabel mobileLbl;
    private javax.swing.JTextField nameInput;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JPasswordField passwordInput;
    private javax.swing.JLabel passwordLbl;
    private javax.swing.JButton saveChangeBtn;
    // End of variables declaration//GEN-END:variables
}
